apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "postgresql://auth_admin:8%28i0DhQiJEf4vV%5D%7D@togglemaster-prod-auth-db.cmj6wucmyhww.us-east-1.rds.amazonaws.com:5432/auth_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: flags-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "postgresql://flags_admin:aOb%25P%21BO8JMZ%2BxNd@togglemaster-prod-flags-db.cmj6wucmyhww.us-east-1.rds.amazonaws.com:5432/flags_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "postgresql://targeting_admin:Z%2A%21uW%2A%3CvZZbj6ozZ@togglemaster-prod-targeting-db.cmj6wucmyhww.us-east-1.rds.amazonaws.com:5432/targeting_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "redis://togglemaster-prod-redis.jq7hds.0001.use1.cache.amazonaws.com:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: togglemaster
type: Opaque
stringData:
  master-key: "admin-secreto-123"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secrets
  namespace: togglemaster
type: Opaque
stringData:
  api-key: "tm_key_production_secret"
