apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "postgresql://auth_admin:NM8%3Cgbdv4j-f9It%5D@togglemaster-prod-auth-db.cvervqr8mz7x.us-east-1.rds.amazonaws.com:5432/auth_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: flags-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "postgresql://flags_admin:czOACax%5B%2AXjg%3C%231q@togglemaster-prod-flags-db.cvervqr8mz7x.us-east-1.rds.amazonaws.com:5432/flags_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "postgresql://targeting_admin:V6u%28%5B7%3E_1n%23i%7BMAb@togglemaster-prod-targeting-db.cvervqr8mz7x.us-east-1.rds.amazonaws.com:5432/targeting_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: togglemaster
type: Opaque
stringData:
  url: "redis://togglemaster-prod-redis.8cbbv2.0001.use1.cache.amazonaws.com:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: togglemaster
type: Opaque
stringData:
  master-key: "admin-secreto-123"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secrets
  namespace: togglemaster
type: Opaque
stringData:
  api-key: "tm_key_production_secret"
